services:
  task_app_back:
    container_name: "task_app"
    ports:
      - "8000:8000"
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: 'task_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"


  booking_celery_beat_service:
    container_name: 'task_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true